# Generated by Django 6.0.2 on 2026-02-16 09:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='videos/'),
        ),
    ]
